import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Harman Singh - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // you can remove `className={inter.className}`, and it will look exactly the same as the old version
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
